
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import AuthProvider from "../context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NO-CAP MESSAGES",
  description: "Generated by Rahul",
  icons:"next.svg",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <AuthProvider>
      <body className={inter.className}>
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
